# Pipeline 100% Cloud - SpaceData Monitor
trigger:
- main

pool:
  vmImage: 'ubuntu-latest' # Agora estamos usando a máquina da Microsoft!

variables:
  # Conexões
  dockerRegistryServiceConnection: '773296bf-4438-4241-a803-e937d645a22f'
  azureServiceConnection: 'ConexaoAzure' # A conexão que acabamos de criar no Passo 2
  
  # Variáveis do Projeto
  rgName: 'rg-space'
  acrName: 'rcspacedata'
  imageName: 'spacedatamonitor'
  aciName: 'aci-spacedata'
  dnsLabel: 'spacedata-$(Build.BuildId)' 
  tag: '$(Build.BuildId)'

steps:
# TAREFA 2: Build e Push
- task: Docker@2
  displayName: '1. Build e Push da Imagem para o ACR'
  inputs:
    command: buildAndPush
    repository: $(imageName)
    dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    containerRegistry: $(dockerRegistryServiceConnection)
    tags: |
      $(tag)

# TAREFA 3 e 4: Deploy no ACI usando a tarefa oficial do Azure CLI
- task: AzureCLI@2
  displayName: '2. Deploy no ACI (Azure Container Instance)'
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Iniciando implantação no Azure Container Instance na Nuvem..."

      # 1. Recuperando credenciais do ACR (O comando az já está autenticado pela Service Connection)
      ACR_LOGIN_SERVER=$(az acr show --name $(acrName) --query loginServer --output tsv | tr -d '\r')
      ACR_USERNAME=$(az acr credential show --name $(acrName) --query username --output tsv | tr -d '\r')
      ACR_PASSWORD=$(az acr credential show --name $(acrName) --query "passwords[0].value" --output tsv | tr -d '\r')

      # 2. Prevenção de conflito
      az container delete --resource-group $(rgName) --name $(aciName) --yes || true

      # 3. Criação da máquina
      az container create \
        --resource-group $(rgName) \
        --name $(aciName) \
        --image $ACR_LOGIN_SERVER/$(imageName):$(tag) \
        --dns-name-label $(dnsLabel) \
        --ports 8080 \
        --registry-login-server $ACR_LOGIN_SERVER \
        --registry-username $ACR_USERNAME \
        --registry-password $ACR_PASSWORD \
        --os-type Linux \
        --cpu 1 \
        --memory 2

      # 4. Link público final
      FQDN=$(az container show --resource-group $(rgName) --name $(aciName) --query ipAddress.fqdn --output tsv | tr -d '\r')
      
      echo "========================================================"
      echo "🚀 APLICAÇÃO PUBLICADA COM SUCESSO!"
      echo "🔗 LINK PARA O BROWSER: http://$FQDN:8080"
      echo "========================================================"